import Code.com.javiersc.kotlin.stdlib.tree.TreeNode
import PredictableAnalysis.Tactic.AnalyzeDecl
import PredictableAnalysis.Tactic.VerifyProperty

set_option mvcgen.warning false

open Std.Do

#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.ChildDeclarationInterface.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNodeException.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.«<get-parent>»
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.«<get-children>»
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.«<get-isRoot>»
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.addChild
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.removeChild
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.«<get-nodeCount>»
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.«<get-height>»
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.clear
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.print
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.iterator
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNodeException.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.«<get-root>»
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.child
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.«<get-depth>»
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.path
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.prettyString
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNodeKt.tree
#analyze_decl Code.com.javiersc.kotlin.stdlib.tree.TreeNode.lambda_135
#verify_invariants Code.com.javiersc.kotlin.stdlib.tree.TreeNode
#verify_invariants Code.com.javiersc.kotlin.stdlib.tree.ChildDeclarationInterface
#verify_invariants Code.com.javiersc.kotlin.stdlib.tree.TreeNodeException
#verify_invariants Code.com.javiersc.kotlin.stdlib.tree.TreeNodeKt
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.new
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.ChildDeclarationInterface.new
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNodeException.new
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.«<get-parent>»
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.«<get-children>»
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.«<get-isRoot>»
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.addChild
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.removeChild
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.«<get-nodeCount>»
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.«<get-height>»
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.clear
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.print
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.iterator
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNodeException.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.«<get-root>»
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.child
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.«<get-depth>»
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.path
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.prettyString
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNodeKt.tree
#verify_returns Code.com.javiersc.kotlin.stdlib.tree.TreeNode.lambda_135
