import Code.com.javiersc.kotlin.stdlib.graph.Graph
import PredictableAnalysis.Tactic.AnalyzeDecl
import PredictableAnalysis.Tactic.VerifyProperty

set_option mvcgen.warning false

open Std.Do

#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.Vertex.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.Edge.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.asString
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.contains
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.contains_1
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.vertexesFor_1
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.renderer
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.Vertex.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.Vertex.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.Edge.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.Edge.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.«<get-entries>»
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.«<get-keys>»
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.«<get-size>»
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.«<get-values>»
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.isEmpty
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.get
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.containsValue
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.containsKey
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.lambda_19
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.lambda_26
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.lambda_133
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.Edge.constructor_1
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.addVertex
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.GraphKt.buildGraph
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.GraphKt.mutableGraphOf
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.deepFirstSearchCircularDependencies
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.addEdge
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.lambda_128
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.toGraphSortedByEdges
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.containsCircularVertexes
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.doesNotContainsCircularVertexes
#analyze_decl Code.com.javiersc.kotlin.stdlib.graph.Graph.vertexesFor
#verify_invariants Code.com.javiersc.kotlin.stdlib.graph.Graph
#verify_invariants Code.com.javiersc.kotlin.stdlib.graph.Graph.Vertex
#verify_invariants Code.com.javiersc.kotlin.stdlib.graph.Graph.Edge
#verify_invariants Code.com.javiersc.kotlin.stdlib.graph.MutableGraph
#verify_invariants Code.com.javiersc.kotlin.stdlib.graph.GraphKt
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.new
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.Vertex.new
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.Edge.new
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.new
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.asString
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.contains
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.contains_1
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.vertexesFor_1
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.renderer
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.Vertex.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.Vertex.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.Edge.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.Edge.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.«<get-entries>»
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.«<get-keys>»
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.«<get-size>»
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.«<get-values>»
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.isEmpty
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.get
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.containsValue
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.containsKey
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.lambda_19
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.lambda_26
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.lambda_133
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.Edge.constructor_1
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.addVertex
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.GraphKt.buildGraph
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.GraphKt.mutableGraphOf
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.deepFirstSearchCircularDependencies
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.MutableGraph.addEdge
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.lambda_128
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.toGraphSortedByEdges
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.containsCircularVertexes
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.doesNotContainsCircularVertexes
#verify_returns Code.com.javiersc.kotlin.stdlib.graph.Graph.vertexesFor
