import Code.com.javiersc.kotlin.stdlib.AnsiColors
import PredictableAnalysis.Tactic.AnalyzeDecl
import PredictableAnalysis.Tactic.VerifyProperty

set_option mvcgen.warning false

open Std.Do

#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Reset.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Black.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Red.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Green.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Yellow.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Blue.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Purple.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Cyan.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.White.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightBlack.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightRed.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightGreen.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightYellow.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightBlue.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightPurple.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightCyan.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightWhite.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Black.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Red.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Green.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Yellow.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Blue.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Purple.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Cyan.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Gray.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColorsKt.ansiColor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Reset.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Black.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Red.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Green.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Yellow.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Blue.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Purple.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Cyan.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.White.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightBlack.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightRed.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightGreen.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightYellow.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightBlue.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightPurple.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightCyan.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightWhite.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Black.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Red.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Green.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Yellow.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Blue.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Purple.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Cyan.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Gray.constructor
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Reset
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Black
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Red
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Green
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Yellow
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Blue
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Purple
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Cyan
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.White
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightBlack
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightRed
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightGreen
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightYellow
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightBlue
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightPurple
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightCyan
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightWhite
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Background
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Black
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Red
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Green
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Yellow
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Blue
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Purple
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Cyan
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Gray
#verify_invariants Code.com.javiersc.kotlin.stdlib.AnsiColorsKt
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Reset.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Black.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Red.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Green.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Yellow.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Blue.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Purple.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Cyan.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.White.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightBlack.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightRed.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightGreen.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightYellow.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightBlue.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightPurple.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightCyan.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightWhite.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Black.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Red.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Green.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Yellow.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Blue.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Purple.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Cyan.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Gray.new
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColorsKt.ansiColor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Reset.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Black.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Red.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Green.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Yellow.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Blue.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Purple.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.Cyan.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.White.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightBlack.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightRed.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightGreen.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightYellow.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightBlue.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightPurple.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightCyan.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Foreground.BrightWhite.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Black.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Red.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Green.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Yellow.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Blue.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Purple.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Cyan.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.AnsiColor.Background.Gray.constructor
