import Code.com.javiersc.kotlin.stdlib.Either
import PredictableAnalysis.Tactic.AnalyzeDecl
import PredictableAnalysis.Tactic.VerifyProperty

set_option mvcgen.warning false

open Std.Do

#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.Left.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.Left.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.Right.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.Right.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.isLeft
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.isRight
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.isLeft_1
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.isRight_1
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.fold
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.Left.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.Left.Companion.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.Right.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.Right.Companion.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.EitherKt.flatMap
#analyze_decl Code.com.javiersc.kotlin.stdlib.EitherKt.handleErrorWith
#analyze_decl Code.com.javiersc.kotlin.stdlib.EitherKt.getOrElse
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.lambda_245
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.lambda_268
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.lambda_287
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.lambda_287_2
#analyze_decl Code.com.javiersc.kotlin.stdlib.EitherKt.lambda_372
#analyze_decl Code.com.javiersc.kotlin.stdlib.EitherKt.lambda_373
#analyze_decl Code.com.javiersc.kotlin.stdlib.EitherKt.lambda_400
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.onRight
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.onLeft
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.getOrNull
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.leftOrNull
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.Left.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.Right.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.EitherKt.flatten
#analyze_decl Code.com.javiersc.kotlin.stdlib.EitherKt.merge
#analyze_decl Code.com.javiersc.kotlin.stdlib.EitherKt.compareTo
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.swap
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.map
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.mapLeft
#analyze_decl Code.com.javiersc.kotlin.stdlib.EitherKt.left
#analyze_decl Code.com.javiersc.kotlin.stdlib.EitherKt.right
#analyze_decl Code.com.javiersc.kotlin.stdlib.EitherKt.combine
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.lambda_140
#analyze_decl Code.com.javiersc.kotlin.stdlib.Either.lambda_140_2
#analyze_decl Code.com.javiersc.kotlin.stdlib.EitherKt.toEitherNel
#analyze_decl Code.com.javiersc.kotlin.stdlib.EitherKt.leftNel
#verify_invariants Code.com.javiersc.kotlin.stdlib.Either
#verify_invariants Code.com.javiersc.kotlin.stdlib.Either.Left
#verify_invariants Code.com.javiersc.kotlin.stdlib.Either.Left.Companion
#verify_invariants Code.com.javiersc.kotlin.stdlib.Either.Right
#verify_invariants Code.com.javiersc.kotlin.stdlib.Either.Right.Companion
#verify_invariants Code.com.javiersc.kotlin.stdlib.EitherKt
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.Left.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.Left.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.Right.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.Right.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.isLeft
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.isRight
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.isLeft_1
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.isRight_1
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.fold
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.Left.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.Left.Companion.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.Right.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.Right.Companion.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.EitherKt.flatMap
#verify_returns Code.com.javiersc.kotlin.stdlib.EitherKt.handleErrorWith
#verify_returns Code.com.javiersc.kotlin.stdlib.EitherKt.getOrElse
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.lambda_245
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.lambda_268
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.lambda_287
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.lambda_287_2
#verify_returns Code.com.javiersc.kotlin.stdlib.EitherKt.lambda_372
#verify_returns Code.com.javiersc.kotlin.stdlib.EitherKt.lambda_373
#verify_returns Code.com.javiersc.kotlin.stdlib.EitherKt.lambda_400
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.onRight
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.onLeft
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.getOrNull
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.leftOrNull
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.Left.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.Right.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.EitherKt.flatten
#verify_returns Code.com.javiersc.kotlin.stdlib.EitherKt.merge
#verify_returns Code.com.javiersc.kotlin.stdlib.EitherKt.compareTo
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.swap
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.map
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.mapLeft
#verify_returns Code.com.javiersc.kotlin.stdlib.EitherKt.left
#verify_returns Code.com.javiersc.kotlin.stdlib.EitherKt.right
#verify_returns Code.com.javiersc.kotlin.stdlib.EitherKt.combine
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.lambda_140
#verify_returns Code.com.javiersc.kotlin.stdlib.Either.lambda_140_2
#verify_returns Code.com.javiersc.kotlin.stdlib.EitherKt.toEitherNel
#verify_returns Code.com.javiersc.kotlin.stdlib.EitherKt.leftNel
