import Code.com.javiersc.kotlin.stdlib.Platform
import PredictableAnalysis.Tactic.AnalyzeDecl
import PredictableAnalysis.Tactic.VerifyProperty

set_option mvcgen.warning false

open Std.Do

#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Android.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Android.Arm32.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Android.Arm64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Android.X64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Android.X86.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Android.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Apple.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Apple.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.IOS.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.IOS.Arm64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.IOS.SimulatorArm64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.IOS.X64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.IOS.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.JVM.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.JVM.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.JS.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.JS.Browser.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.JS.NodeJS.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.JS.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Linux.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Linux.Arm64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Linux.X64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Linux.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.MacOS.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.MacOS.Arm64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.MacOS.X64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.MacOS.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.MinGW.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.MinGW.X64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.MinGW.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Native.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Native.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.TvOS.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.TvOS.Arm64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.TvOS.SimulatorArm64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.TvOS.X64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.TvOS.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.Browser.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.D8.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.NodeJS.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.WAsi.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.WAsi.NodeJS.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.WAsi.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.Arm32.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.Arm64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.DeviceArm64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.SimulatorArm64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.X64.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.Companion.new
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Android.Arm32.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Android.Arm64.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Android.X64.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Android.X86.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Android.Companion.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Android.Companion.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Apple.Companion.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Apple.Companion.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.IOS.Arm64.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.IOS.SimulatorArm64.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.IOS.X64.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.IOS.Companion.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.IOS.Companion.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.JVM.Companion.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.JVM.Companion.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.JS.Browser.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.JS.NodeJS.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.JS.Companion.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.JS.Companion.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Linux.Arm64.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Linux.X64.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Linux.Companion.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Linux.Companion.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.MacOS.Arm64.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.MacOS.X64.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.MacOS.Companion.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.MacOS.Companion.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.MinGW.X64.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.MinGW.Companion.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.MinGW.Companion.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Native.Companion.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.Native.Companion.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.TvOS.Arm64.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.TvOS.SimulatorArm64.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.TvOS.X64.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.TvOS.Companion.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.TvOS.Companion.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.Browser.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.D8.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.NodeJS.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.Companion.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.Companion.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.WAsi.NodeJS.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.WAsi.Companion.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.WAsi.Companion.toString
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.Companion.constructor
#analyze_decl Code.com.javiersc.kotlin.stdlib.Platform.WAsm.Companion.toString
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.Android
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.Android.Arm32
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.Android.Arm64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.Android.X64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.Android.X86
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.Android.Companion
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.Apple
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.Apple.Companion
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.IOS
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.IOS.Arm64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.IOS.SimulatorArm64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.IOS.X64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.IOS.Companion
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.JVM
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.JVM.Companion
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.JS
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.JS.Browser
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.JS.NodeJS
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.JS.Companion
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.Linux
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.Linux.Arm64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.Linux.X64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.Linux.Companion
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.MacOS
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.MacOS.Arm64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.MacOS.X64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.MacOS.Companion
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.MinGW
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.MinGW.X64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.MinGW.Companion
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.Native
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.Native.Companion
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.TvOS
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.TvOS.Arm64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.TvOS.SimulatorArm64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.TvOS.X64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.TvOS.Companion
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WAsm
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.Browser
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.D8
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.NodeJS
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.Companion
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WAsm.WAsi
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WAsm.WAsi.NodeJS
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WAsm.WAsi.Companion
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WAsm.Companion
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WatchOS
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.Arm32
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.Arm64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.DeviceArm64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.SimulatorArm64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.X64
#verify_invariants Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.Companion
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Android.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Android.Arm32.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Android.Arm64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Android.X64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Android.X86.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Android.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Apple.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Apple.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.IOS.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.IOS.Arm64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.IOS.SimulatorArm64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.IOS.X64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.IOS.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.JVM.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.JVM.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.JS.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.JS.Browser.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.JS.NodeJS.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.JS.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Linux.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Linux.Arm64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Linux.X64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Linux.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.MacOS.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.MacOS.Arm64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.MacOS.X64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.MacOS.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.MinGW.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.MinGW.X64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.MinGW.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Native.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Native.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.TvOS.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.TvOS.Arm64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.TvOS.SimulatorArm64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.TvOS.X64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.TvOS.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.Browser.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.D8.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.NodeJS.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.WAsi.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.WAsi.NodeJS.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.WAsi.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.Arm32.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.Arm64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.DeviceArm64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.SimulatorArm64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.X64.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WatchOS.Companion.new
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Android.Arm32.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Android.Arm64.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Android.X64.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Android.X86.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Android.Companion.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Android.Companion.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Apple.Companion.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Apple.Companion.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.IOS.Arm64.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.IOS.SimulatorArm64.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.IOS.X64.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.IOS.Companion.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.IOS.Companion.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.JVM.Companion.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.JVM.Companion.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.JS.Browser.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.JS.NodeJS.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.JS.Companion.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.JS.Companion.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Linux.Arm64.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Linux.X64.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Linux.Companion.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Linux.Companion.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.MacOS.Arm64.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.MacOS.X64.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.MacOS.Companion.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.MacOS.Companion.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.MinGW.X64.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.MinGW.Companion.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.MinGW.Companion.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Native.Companion.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.Native.Companion.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.TvOS.Arm64.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.TvOS.SimulatorArm64.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.TvOS.X64.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.TvOS.Companion.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.TvOS.Companion.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.Browser.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.D8.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.NodeJS.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.Companion.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.JS.Companion.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.WAsi.NodeJS.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.WAsi.Companion.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.WAsi.Companion.toString
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.Companion.constructor
#verify_returns Code.com.javiersc.kotlin.stdlib.Platform.WAsm.Companion.toString
